---
title: "Beatles’s Studio Album Text Mining Analysis"
author: "Douglas Zickuhr"
date: "11/8/2018"
output: html_document
---

```{r loading libraries}
library(tidyverse)
library(tidytext)
library(wordcloud)
library(dplyr)
library(scales)
library(knitr)
library(ggraph)
library(igraph)
```


```{r reading dataset}
lyrics <- read_csv("data/beatles_tidy_lyrics.csv")
```


```{r checking the dataset}
kable(head(lyrics))
str(lyrics)
```


```{r ordering albums by releasing date}
album_names <- c("please please me", "with the beatles", "a hard day's night", "beatles for sale",
       "help","rubber soul","revolver","sgt pepper's lonely hearts club band", "magical mystery tour",
       "the beatles (the white album)","yellow submarine", "abbey road", "let it be")  %>%
  str_to_title()

lyrics <- lyrics %>%
  filter(!is.na(word)) %>%
  mutate(album_title = str_to_title(album_title)) %>%
  mutate(album_title = fct_relevel(album_title, !!!album_names))
```


```{r removing stop words, echo=FALSE}
lyrics_no_sw <- lyrics %>%
  anti_join(stop_words,by="word")
```

```{r wordcloud}
set.seed(123)
lyrics_no_sw %>%
  count(word) %>%
  with(wordcloud(words = word, 
                 freq = n,
                 max.words = 100,
                 random.order = FALSE,
                 colors = n
                 ))
```


```{r word frequency}
lyrics_no_sw %>%
  count(word,sort = TRUE) %>%
  top_n(20,n) %>%
  ggplot() +
  geom_bar(aes(x=reorder(word,n),
               y=n,fill=reorder(word,n)),
           show.legend = FALSE,
           stat = "identity") + 
  scale_fill_viridis_d(direction = -1,
                       option = "D",
                       aesthetics = ) +
  coord_flip() + 
  labs(x= "Word",
       y = "Frequency")
```


https://drsimonj.svbtle.com/ordering-categories-within-ggplot2-facets

```{r frequent words by album, fig.height=3}
ordered_lyrics <- lyrics_no_sw %>%
  count(album_title,word) %>%
  group_by(album_title) %>%
  top_n(10,n) %>%
  ungroup() %>%
  arrange(album_title, desc(n)) %>%
  mutate(order = row_number())

ggplot(ordered_lyrics,
       aes(desc(order),n,fill=album_title)) + 
  geom_bar(stat = "identity", show.legend = FALSE) +
  facet_wrap(~album_title, scales = "free") +
  theme_bw() +
  scale_x_continuous(
    breaks = desc(ordered_lyrics$order),
    labels = ordered_lyrics$word,
    expand = c(0,0)
  ) +
  coord_flip() + 
  scale_fill_viridis_d(direction = -1,
                       option = "D") + 
  labs(title = "Word Frequency by Album",
       x = "Word",
       y = "Frequency")
```

```{r tf-idf, fig.height=3}
ordered_tfidf <- lyrics_no_sw %>%
  count(album_title,word) %>%
  bind_tf_idf(word,album_title,n) %>%
  arrange(desc(tf_idf)) %>%
  group_by(album_title) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(order = row_number())


  ggplot(ordered_tfidf,
         aes(desc(order),tf_idf,fill=album_title)) + 
  geom_bar(stat = "identity", show.legend = FALSE) +
  facet_wrap(~album_title, scales = "free") +
  theme_bw() +
  scale_x_continuous(
    breaks = desc(ordered_tfidf$order),
    labels = ordered_tfidf$word,
    expand = c(0,0)
  ) +
  coord_flip() + 
  scale_fill_viridis_d(direction = -1,
                       option = "D") + 
    labs(title = "Relevant words by Album",
         x = "Word",
         y = "TF-IDF")

```


```{r sentiment by album}
nrc <- get_sentiments("nrc")

sentiments <- c("Negative","Anger","Disgust","Sadness","Fear","Anticipation","Surprise","Joy","Trust","Positive")

sentiment_by_album <- lyrics_no_sw %>%
  inner_join(nrc,by="word") %>%
  mutate(sentiment = str_to_title(sentiment)) %>%
  mutate(sentiment = fct_relevel(sentiment, !!!sentiments)) %>%
  group_by(album_title,sentiment) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n)) %>%
  ungroup()
```


```{r radar plot of sentiment by album, fig.height=3 }
source("radar-plot.R")
sentiment_by_album %>%
  select(album_title,sentiment,freq) %>%
  spread(sentiment,freq) %>%
  rename(group = album_title) %>%
  mutate_if(is.numeric,scale,center=FALSE) %>%
  as.data.frame() %>%
  radar_plot(grid.max = 1.8,
             legend.title = "Album",
             palette = scale_color_viridis_d(direction = -1,
                                             option = "D"),
             labs = labs(title="Sentiment Analaysis of Beatles's Studio Album"),
             label.gridline.min = FALSE,
             label.gridline.mid = FALSE,
             label.gridline.max = FALSE)
```

```{r heatmap, fig.height=3 }
sentiment_by_album %>%
  arrange(album_title,desc(freq)) %>%
  mutate(album_title = fct_rev(album_title)) %>%
  ggplot(aes(sentiment,
             album_title,
             fill=freq)) +
  geom_tile() +
  scale_fill_viridis_c(direction = -1,
                        option = "D") + 
  theme(axis.text.x = element_text(angle=45,
                                   hjust = 1)) + 
  labs(title = "Heatmap of Sentiment by Album",
       fill = "Frequency of Sentiment",
       x = "Sentiment",
       y = "Album")
  
  
```


```{r}
sentiment_by_track <- lyrics_no_sw %>%
  inner_join(nrc,by="word") %>%
  mutate(sentiment = str_to_title(sentiment)) %>%
  group_by(album_title,track_n,sentiment) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n)) %>%
  ungroup()

```


```{r sentiment plot by track by album, fig.height=3}
sentiment_by_track %>%
{ggplot(data = .) + 
  geom_bar(aes(x=factor(track_n),y=freq,group=sentiment,fill=sentiment),
           stat = "identity",
           position = "stack") + 
  facet_wrap(~album_title,
             scales="free_x",
             ncol = 3) + 
  scale_fill_viridis_d(direction = 1,
                        option = "D") + 
  labs(title = "Heatmap of Sentiment by Album",
       fill = "Frequency of Sentiment",
       x = "Sentiment",
       y = "Album")}
  

```

```{r}
lyrics_untidy <- read_csv("data/beatles_lyrics.csv")

lyrics_ngram <- lyrics_untidy %>%
  unnest_tokens(two_words,lyric,token="ngrams",n=2) %>%
  separate(two_words, c("word1","word2"), " ") %>%
  filter(!word1 %in% stop_words$word & !is.na(word1)) %>%
  filter(!word2 %in% stop_words$word & !is.na(word2)) %>%
  unite(two_words,word1,word2, sep = " ")
```


```{r}
lyrics_ngram %>%
  count(album_title,two_words) %>%
  separate(two_words,c("word1","word2"),sep = " ") %>%
  select(word1,word2,n) %>%
  filter(n > 10) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(n = 5) +
  geom_node_point() +
  geom_node_text(aes(label = name), 
                 vjust = 1, 
                 hjust = 1) + 
  theme_bw()
  
```


