---
title: "TidyTuesday 2019 6"
author: "Douglas Zickuhr"
date: "4/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(dplyr)
library(sf)
library(ggplot2)
library(stringr)
library(gganimate)
theme_set(theme_void())
```


```{r}
hpi <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-05/state_hpi.csv")
```

```{r}
usa <- st_read("/Users/douglaszickuhr/Downloads/cb_2017_us_state_20m/cb_2017_us_state_20m.shp")
```

```{r}
<<<<<<< HEAD
states <- as_tibble(cbind(abb = datasets::state.abb,name = datasets::state.name))

usa %>% 
  left_join(hpi, by = c("STUSPS" = "state")) %>%
  filter(!STUSPS %in% c("AK","HI")) %>%
  filter(year == 1975) %>%
  mutate(date = lubridate::make_date(year,month,1)) %>%
  ggplot() + 
  geom_sf(aes(fill = price_index)) + 
  
  

=======
>>>>>>> 51c943c91a880139cfd8384a2aeb08f45192ef12
p <- usa %>% 
  left_join(hpi, by = c("STUSPS" = "state")) %>%
  filter(!STUSPS %in% c("AK","HI")) %>%
  filter(year <= 2019) %>%
  mutate(date = lubridate::make_date(year,month,1)) %>%
  ggplot() + 
  geom_sf(aes(fill = price_index)) + 
  labs(fill = "Price Index",
       title = 'Houses Price Index: {format.Date(frame_time,"%m/%Y")}') +
  scale_fill_viridis_c(direction = -1) +
  theme(panel.grid.major = element_line(colour="transparent")) +
  transition_time(date) 

anim <- animate(plot = p,
        nframes = 516,
        duration = 12)

anim_save(anim, file = "/Users/douglaszickuhr/Documents/test.gif")
```

