---
title: "week29"
author: "Douglas Zickuhr"
date: "18/10/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
library(reshape2)
library(janitor)
theme_set(theme_light())
```

```{r}
major_salary <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018-10-16/recent-grads.csv") %>%
  mutate(Major = str_to_title(Major)) %>%
  clean_names()
  
```

# Removing majors where the # of sample is less than 100
```{r}
major_salary_sampled <- major_salary %>%
  filter(sample_size >= 100)  
```


# What are the major with the highest unemployement rate?
```{r}
major_salary_sampled %>%
  arrange(desc(unemployment_rate)) %>%
  mutate(major = fct_reorder(major,unemployment_rate)) %>%
  head(20) %>%
  ggplot() + 
  geom_col(aes(x=major,y=unemployment_rate),fill="black") + 
  scale_y_continuous(labels = scales::percent) +
  coord_flip() + 
  labs(title = "What are majors with the highest unmployment rate?",
       subtitle = "Top 20 Majors",
       x = "Major",
       y = "Unemployement Rate")
```

# What's the participation of women by Major Category?
```{r}
major_salary %>%
  group_by(major_category) %>%
  summarise(men = sum(men,na.rm = TRUE),
            women = sum(women,na.rm = TRUE),
            grand_total = men + women,
            men = men/grand_total,
            women = women/grand_total) %>%
  select(-grand_total) %>%
  mutate(major_category = fct_reorder(major_category,women)) %>%
  melt(id.vars = c("major_category"),
       variable.name = "genre",
       value.name = "rate") %>%
  ggplot(aes(x=major_category,y=rate,group=genre,fill=genre)) +
  geom_bar(stat = "identity",
           position = "stack") + 
  coord_flip() + 
  labs(title = "Genres Participation",
       subtitle = "By Major Category",
       x = "Major Category",
       y = "Genre Rate") + 
  scale_y_continuous(labels = scales::percent)
  
```


```{r}
major_salary %>%
  group_by(major_category) %>%
  summarise(median = median(median),
            p25th = median(p25th),
            p75th = median(p75th)) %>% 
  mutate(major_category = fct_reorder(major_category,median)) %>%
  ggplot() + 
  geom_point(aes(x=major_category,y=median)) + 
  geom_errorbar(aes(x=major_category,ymax=p75th,ymin=p25th)) + 
  coord_flip()
```

