---
title: "Week18"
author: "Douglas Zickuhr"
date: "2/8/2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

## Reading the spreadsheet into R
```{r reading excel spreadsheet}
animals <- readxl::read_xlsx(path = "tidytuesday/data/week18_dallas_animals.xlsx",
                             sheet = "simple")
```


### Analysing the intake of Dogs and Cats across the year.

Apparently there is a sad pattern of abbandoned animals during the summer
```{r animals intake plot echo=FALSE}
p1 <- animals %>%
  dplyr::filter(animal_type %in% c("CAT","DOG")) %>%
  dplyr::filter(intake_type %in% c("STRAY","OWNER SURRENDER")) %>%
  dplyr::mutate(intake_type = factor(intake_type),
         animal_type = factor(animal_type),
         intake_type = forcats::fct_recode(intake_type, "Stray" = "STRAY",
                                  "Owner Surrender" = "OWNER SURRENDER"),
         animal_type = forcats::fct_recode(animal_type, "Dog" = "DOG",
                                  "Cat" = "CAT")) %>%
  dplyr::group_by(intake_type,animal_type,intake_date) %>%
  dplyr::summarise(number = dplyr::n()) %>%
  ggplot2::ggplot(ggplot2::aes(x=intake_date,y=number,group=animal_type,colour=animal_type)) + 
  ggplot2::geom_line(alpha = 0.2) + 
  ggplot2::geom_smooth(method = "loess") + 
  ggplot2::facet_wrap(~intake_type, 
             scales = "free_y", 
             ncol = 1) + 
  ggplot2::theme_minimal() + 
  ggplot2::scale_colour_brewer(palette = "Set1") + 
  ggplot2::labs(title = "Abbandoned Animals Intake by Intake Date",
       x = "Intake Date",
       y = "Number of Animals",
       colour = "Animal Type")

ggplot2::ggsave(filename = "Week18-1.png",
       plot = p1)
  
p1
```

### Analysing the outcome of Dogs and Cats during the year.

Visually, there is a tendency of Dogs to be more adopted than cats.

```{r pressure, echo=FALSE}
p2 <- animals %>%
  dplyr::filter(animal_type %in% c("CAT","DOG")) %>%
  dplyr::filter(intake_type %in% c("STRAY","OWNER SURRENDER")) %>%
  dplyr::mutate(animal_type = factor(stringr::str_to_title(animal_type)),
         outcome_type = factor(stringr::str_to_title(outcome_type))) %>%
  dplyr::mutate(outcome_type = forcats::fct_lump(outcome_type, n = 5),
         month = lubridate::month(intake_date,label = TRUE)) %>%
  dplyr::group_by(month,outcome_type,animal_type) %>%
  dplyr::summarise(total = dplyr::n()) %>%
  ggplot2::ggplot() +
  ggplot2::geom_area(ggplot2::aes(x=month, y=total,group = outcome_type, fill = outcome_type)) + 
  ggplot2::facet_wrap(~animal_type, ncol = 1, scales = "free_y") + 
  ggplot2::theme_minimal() + 
  ggplot2::scale_fill_brewer(palette = "Set1")+ 
  ggplot2::labs(title = "Abbandoned Animals Outcome by Month",
       x = "Month",
       y = "Number of Animals",
       colour = "Outcome")

ggplot2::ggsave(filename = "Week18-2.png",
       plot = p2)
  
p2
```

